worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format questionnaire_frontend '$remote_addr - $time_local "$request" '
                                    'status=$status bytes=$body_bytes_sent '
                                    'referer="$http_referer" user_agent="$http_user_agent"';

  sendfile on;
  keepalive_timeout 65;

  include /etc/nginx/conf.d/*.conf;
}
